---

metrics:
  port: 9090 # port for prometheus metrics, served on /metrics and /

gateways:
  - configFile: "config_holesky.yml"
    name: "Holesky gateway"
  - configFile: "config_sepolia.yml"
    name: "Sepolia gateway"