{
 "title": "RPC gateway",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Block Number (Holesky)",
   "type": "graph",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "zeroex_rpc_gateway_provider_block_number_Holesky",
     "legendFormat": "{{provider}}"
    }
   ]
  },
  {
   "title": "Block Number (Sepolia)",
   "type": "graph",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "zeroex_rpc_gateway_provider_block_number_Sepolia",
     "legendFormat": "{{provider}}"
    }
   ]
  },
  {
   "title": "Gas Limit (Holesky)",
   "type": "graph",
   "gridPos": { "x": 0, "y": 8, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "zeroex_rpc_gateway_provider_gasLimit_number_Holesky",
     "legendFormat": "{{provider}}"
    }
   ]
  },
  {
   "title": "Gas Limit (Sepolia)",
   "type": "graph",
   "gridPos": { "x": 12, "y": 8, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "zeroex_rpc_gateway_provider_gasLimit_number_Sepolia",
     "legendFormat": "{{provider}}"
    }
   ]
  },
  {
   "title": "Provider Info (Holesky)",
   "type": "graph",
   "gridPos": { "x": 0, "y": 16, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "zeroex_rpc_gateway_provider_info_Holesky",
     "legendFormat": "{{provider}} (Index {{index}})"
    }
   ]
  },
  {
   "title": "Provider Info (Sepolia)",
   "type": "graph",
   "gridPos": { "x": 12, "y": 16, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "zeroex_rpc_gateway_provider_info_Sepolia",
     "legendFormat": "{{provider}} (Index {{index}})"
    }
   ]
  },
  {
   "title": "Provider Status (Holesky)",
   "type": "graph",
   "gridPos": { "x": 0, "y": 24, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "zeroex_rpc_gateway_provider_status_Holesky",
     "legendFormat": "{{provider}} ({{type}})"
    }
   ]
  },
  {
   "title": "Provider Status (Sepolia)",
   "type": "graph",
   "gridPos": { "x": 12, "y": 24, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "zeroex_rpc_gateway_provider_status_Sepolia",
     "legendFormat": "{{provider}} ({{type}})"
    }
   ]
  }
 ]
}